"""Tests for the report generation engine (HTML rendering).

These tests validate HTML template rendering without requiring WeasyPrint.
"""
from __future__ import annotations

import pytest

from backend.engine.report_engine import (
    WEASYPRINT_AVAILABLE,
    render_html,
    render_pdf,
)


# ---------------------------------------------------------------------------
# QC Report Template
# ---------------------------------------------------------------------------

class TestQCReportHTML:
    """Tests for qc_report.html template rendering."""

    def _sample_context(self) -> dict:
        return {
            "run_id": "run-abc-123",
            "assay": "COVID-19 IgG",
            "instrument": "QuantStudio 5",
            "uploaded_at": "2025-06-15T10:30:00",
            "reagent_lot_id": "RL-2025-001",
            "control_lot_id": "CL-2025-042",
            "file_name": "qc_run_20250615.xlsx",
            "file_hash": "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6abcd",
            "run_status": "reject",
            "first_reject_rule": "1-3s",
            "summary_stats": {
                "mean_z": 0.523,
                "max_z": 3.456,
                "min_z": -0.891,
                "point_count": 10,
            },
            "violations": [
                {
                    "sequence_index": 3,
                    "control_level": "Level 1",
                    "ct_value": 25.4,
                    "z_score": 3.456,
                    "rules": ["1-2s", "1-3s"],
                },
            ],
            "data_points": [
                {
                    "sequence_index": 0,
                    "control_level": "Level 1",
                    "ct_value": 22.5,
                    "mean": 22.0,
                    "sd": 0.5,
                    "z_score": 1.0,
                    "violations": [],
                },
                {
                    "sequence_index": 1,
                    "control_level": "Level 2",
                    "ct_value": 28.1,
                    "mean": 28.0,
                    "sd": 0.3,
                    "z_score": 0.333,
                    "violations": [],
                },
            ],
        }

    def test_render_contains_run_id(self):
        html = render_html("qc_report.html", self._sample_context())
        assert "run-abc-123" in html

    def test_render_contains_assay(self):
        html = render_html("qc_report.html", self._sample_context())
        assert "COVID-19 IgG" in html

    def test_render_contains_instrument(self):
        html = render_html("qc_report.html", self._sample_context())
        assert "QuantStudio 5" in html

    def test_render_contains_status(self):
        html = render_html("qc_report.html", self._sample_context())
        assert "REJECT" in html

    def test_render_contains_first_reject_rule(self):
        html = render_html("qc_report.html", self._sample_context())
        assert "1-3s" in html

    def test_render_contains_violation_data(self):
        html = render_html("qc_report.html", self._sample_context())
        assert "3.456" in html
        assert "1-2s, 1-3s" in html

    def test_render_contains_data_points(self):
        html = render_html("qc_report.html", self._sample_context())
        assert "22.50" in html
        assert "Level 1" in html
        assert "Level 2" in html

    def test_render_contains_summary_stats(self):
        html = render_html("qc_report.html", self._sample_context())
        assert "mean_z" in html
        assert "0.523" in html

    def test_render_contains_reagent_lot(self):
        html = render_html("qc_report.html", self._sample_context())
        assert "RL-2025-001" in html

    def test_render_contains_control_lot(self):
        html = render_html("qc_report.html", self._sample_context())
        assert "CL-2025-042" in html

    def test_render_contains_file_hash(self):
        html = render_html("qc_report.html", self._sample_context())
        assert "a1b2c3d4e5f6" in html

    def test_render_is_valid_html(self):
        html = render_html("qc_report.html", self._sample_context())
        assert html.strip().startswith("<!DOCTYPE html>")
        assert "</html>" in html

    def test_render_contains_generated_at(self):
        html = render_html("qc_report.html", self._sample_context())
        assert "Generated by LabQC" in html

    def test_no_violations_message(self):
        ctx = self._sample_context()
        ctx["violations"] = []
        html = render_html("qc_report.html", ctx)
        assert "No violations detected." in html

    def test_pass_status(self):
        ctx = self._sample_context()
        ctx["run_status"] = "pass"
        ctx["first_reject_rule"] = None
        html = render_html("qc_report.html", ctx)
        assert "PASS" in html

    def test_none_mean_shows_na(self):
        ctx = self._sample_context()
        ctx["data_points"] = [
            {
                "sequence_index": 0,
                "control_level": "Level 1",
                "ct_value": 22.5,
                "mean": None,
                "sd": None,
                "z_score": None,
                "violations": [],
            },
        ]
        html = render_html("qc_report.html", ctx)
        assert "N/A" in html


# ---------------------------------------------------------------------------
# Validation Report Template
# ---------------------------------------------------------------------------

class TestValidationReportHTML:
    """Tests for validation_report.html template rendering."""

    def _sample_context(self) -> dict:
        return {
            "validation_id": "val-xyz-789",
            "dataset_id": "ds-abc-456",
            "file_name": "precision_data.xlsx",
            "validation_type": "precision_intra",
            "overall_status": "pass",
            "calculated_at": "2025-06-15T12:00:00",
            "metrics": [
                {
                    "metric": "intra_cv",
                    "value": 3.25,
                    "threshold": 5.0,
                    "operator": "lte",
                    "status": "pass",
                },
            ],
            "raw_summary": {
                "mean": 22.5,
                "sd": 0.731,
                "cv": 3.25,
                "n": 20,
            },
            "acceptance_criteria": [
                {"metric": "intra_cv", "threshold": 5.0, "operator": "lte"},
            ],
        }

    def test_render_contains_validation_id(self):
        html = render_html("validation_report.html", self._sample_context())
        assert "val-xyz-789" in html

    def test_render_contains_file_name(self):
        html = render_html("validation_report.html", self._sample_context())
        assert "precision_data.xlsx" in html

    def test_render_contains_validation_type(self):
        html = render_html("validation_report.html", self._sample_context())
        assert "precision_intra" in html

    def test_render_contains_overall_status(self):
        html = render_html("validation_report.html", self._sample_context())
        assert "PASS" in html

    def test_render_contains_metric_data(self):
        html = render_html("validation_report.html", self._sample_context())
        assert "intra_cv" in html
        assert "3.2500" in html

    def test_render_contains_raw_summary(self):
        html = render_html("validation_report.html", self._sample_context())
        assert "mean" in html
        assert "22.5" in html

    def test_render_contains_acceptance_criteria(self):
        html = render_html("validation_report.html", self._sample_context())
        assert "lte" in html
        assert "5.0" in html

    def test_render_is_valid_html(self):
        html = render_html("validation_report.html", self._sample_context())
        assert html.strip().startswith("<!DOCTYPE html>")
        assert "</html>" in html

    def test_fail_status(self):
        ctx = self._sample_context()
        ctx["overall_status"] = "fail"
        ctx["metrics"][0]["status"] = "fail"
        html = render_html("validation_report.html", ctx)
        assert "FAIL" in html


# ---------------------------------------------------------------------------
# Sigma Report Template
# ---------------------------------------------------------------------------

class TestSigmaReportHTML:
    """Tests for sigma_report.html template rendering."""

    def _sample_context(self) -> dict:
        return {
            "assay_count": 2,
            "results": [
                {
                    "assay": "HbA1c",
                    "tea_percent": 6.0,
                    "bias_percent": 1.0,
                    "cv_percent": 1.5,
                    "sigma_score": 3.33,
                    "classification": "marginal",
                    "recommended_rules": ["1-3s", "2-2s", "R-4s", "4-1s", "10x"],
                    "nmedx_x": 0.1667,
                    "nmedx_y": 0.2500,
                    "notes": "Intensified QC and shorter review interval recommended",
                },
                {
                    "assay": "Glucose",
                    "tea_percent": 10.0,
                    "bias_percent": 1.0,
                    "cv_percent": 1.2,
                    "sigma_score": 7.50,
                    "classification": "world_class",
                    "recommended_rules": ["1-3s"],
                    "nmedx_x": 0.1000,
                    "nmedx_y": 0.1200,
                    "notes": None,
                },
            ],
        }

    def test_render_contains_assay_names(self):
        html = render_html("sigma_report.html", self._sample_context())
        assert "HbA1c" in html
        assert "Glucose" in html

    def test_render_contains_sigma_scores(self):
        html = render_html("sigma_report.html", self._sample_context())
        assert "3.33" in html
        assert "7.50" in html

    def test_render_contains_classifications(self):
        html = render_html("sigma_report.html", self._sample_context())
        assert "Marginal" in html
        assert "World Class" in html

    def test_render_contains_recommended_rules(self):
        html = render_html("sigma_report.html", self._sample_context())
        assert "1-3s" in html
        assert "2-2s" in html

    def test_render_contains_nmedx_coordinates(self):
        html = render_html("sigma_report.html", self._sample_context())
        assert "0.1667" in html
        assert "0.2500" in html

    def test_render_contains_notes(self):
        html = render_html("sigma_report.html", self._sample_context())
        assert "Intensified QC" in html

    def test_render_contains_assay_count(self):
        html = render_html("sigma_report.html", self._sample_context())
        assert "2" in html

    def test_render_is_valid_html(self):
        html = render_html("sigma_report.html", self._sample_context())
        assert html.strip().startswith("<!DOCTYPE html>")
        assert "</html>" in html

    def test_empty_results(self):
        ctx = {"assay_count": 0, "results": []}
        html = render_html("sigma_report.html", ctx)
        assert "No sigma results available." in html


# ---------------------------------------------------------------------------
# Audit Report Template
# ---------------------------------------------------------------------------

class TestAuditReportHTML:
    """Tests for audit_report.html template rendering."""

    def _sample_context(self) -> dict:
        return {
            "total_entries": 3,
            "chain_verification": {
                "valid": True,
                "first_invalid_id": None,
                "entries_checked": 3,
            },
            "entries": [
                {
                    "id": 1,
                    "timestamp": "2025-06-15T08:00:00",
                    "event_type": "upload",
                    "file_name": "run_001.xlsx",
                    "action_detail": "QC file uploaded",
                    "entry_hash": "abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890",
                },
                {
                    "id": 2,
                    "timestamp": "2025-06-15T09:00:00",
                    "event_type": "analysis",
                    "file_name": None,
                    "action_detail": "Westgard analysis run on run-001",
                    "entry_hash": "1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef",
                },
                {
                    "id": 3,
                    "timestamp": "2025-06-15T10:00:00",
                    "event_type": "export",
                    "file_name": None,
                    "action_detail": "Audit log exported in json format",
                    "entry_hash": "fedcba0987654321fedcba0987654321fedcba0987654321fedcba0987654321",
                },
            ],
        }

    def test_render_contains_total_entries(self):
        html = render_html("audit_report.html", self._sample_context())
        assert "3" in html

    def test_render_contains_chain_status_pass(self):
        html = render_html("audit_report.html", self._sample_context())
        assert "PASS" in html

    def test_render_contains_event_types(self):
        html = render_html("audit_report.html", self._sample_context())
        assert "upload" in html
        assert "analysis" in html
        assert "export" in html

    def test_render_contains_action_details(self):
        html = render_html("audit_report.html", self._sample_context())
        assert "QC file uploaded" in html
        assert "Westgard analysis run" in html

    def test_render_contains_truncated_hash(self):
        html = render_html("audit_report.html", self._sample_context())
        # Hash should be truncated to 16 chars + "..."
        assert "abcdef1234567890..." in html

    def test_render_contains_file_name(self):
        html = render_html("audit_report.html", self._sample_context())
        assert "run_001.xlsx" in html

    def test_render_is_valid_html(self):
        html = render_html("audit_report.html", self._sample_context())
        assert html.strip().startswith("<!DOCTYPE html>")
        assert "</html>" in html

    def test_chain_fail_shows_invalid_id(self):
        ctx = self._sample_context()
        ctx["chain_verification"] = {
            "valid": False,
            "first_invalid_id": 2,
            "entries_checked": 2,
        }
        html = render_html("audit_report.html", ctx)
        assert "FAIL" in html
        assert "First Invalid Entry ID" in html

    def test_empty_entries(self):
        ctx = {
            "total_entries": 0,
            "chain_verification": {"valid": True, "first_invalid_id": None, "entries_checked": 0},
            "entries": [],
        }
        html = render_html("audit_report.html", ctx)
        assert "No audit entries recorded." in html


# ---------------------------------------------------------------------------
# Engine-level tests
# ---------------------------------------------------------------------------

class TestReportEngine:
    """Test report_engine module-level behavior."""

    def test_weasyprint_flag_is_boolean(self):
        assert isinstance(WEASYPRINT_AVAILABLE, bool)

    def test_render_pdf_raises_when_weasyprint_missing(self):
        if not WEASYPRINT_AVAILABLE:
            with pytest.raises(ImportError, match="WeasyPrint"):
                render_pdf("qc_report.html", {
                    "run_id": "test",
                    "assay": "test",
                    "instrument": "test",
                    "uploaded_at": "",
                    "reagent_lot_id": None,
                    "control_lot_id": None,
                    "file_name": "test.xlsx",
                    "file_hash": "abc123",
                    "run_status": "pass",
                    "first_reject_rule": None,
                    "violations": [],
                    "summary_stats": {},
                    "data_points": [],
                })
        else:
            # If WeasyPrint IS installed, just verify render_pdf returns bytes
            result = render_pdf("qc_report.html", {
                "run_id": "test",
                "assay": "test",
                "instrument": "test",
                "uploaded_at": "",
                "reagent_lot_id": None,
                "control_lot_id": None,
                "file_name": "test.xlsx",
                "file_hash": "abc123",
                "run_status": "pass",
                "first_reject_rule": None,
                "violations": [],
                "summary_stats": {},
                "data_points": [],
            })
            assert isinstance(result, bytes)
            assert len(result) > 0

    def test_generated_at_default(self):
        """render_html should set generated_at if not provided."""
        ctx = {
            "total_entries": 0,
            "chain_verification": {"valid": True, "first_invalid_id": None, "entries_checked": 0},
            "entries": [],
        }
        html = render_html("audit_report.html", ctx)
        assert "UTC" in html

    def test_generated_at_custom(self):
        """render_html should use custom generated_at if provided."""
        ctx = {
            "total_entries": 0,
            "chain_verification": {"valid": True, "first_invalid_id": None, "entries_checked": 0},
            "entries": [],
            "generated_at": "2025-01-01 00:00 UTC",
        }
        html = render_html("audit_report.html", ctx)
        assert "2025-01-01 00:00 UTC" in html
